# Usando imagem do python
FROM python:3.9-slim 
 
# Definindo o diretorio dentro do container
WORKDIR /app

# Copiando o arquivo para o container
COPY carguru.py .

# Comando executado quando o container iniciar
CMD ["python", "carguru.py"]



